services:
  bookshelf-api:
      image: carlmurray/bookshelf-api:latest
      ports:
            - "8080:8080"
      depends_on:
            - bookshelf-api-db
      environment:
            - DOCKER=true
            - DB_HOST=bookshelf-api-db
            - DB_USER
            - DB_PASSWORD
            - DB_NAME


  bookshelf-api-db:
        image: carlmurray/bookshelf-api-db:latest
        container_name: bookshelf-api-db
        ports:
            - "1435:1433"
        environment:
            MSSQL_SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
