services:
  bookshelf-api:
      image: carlmurray/bookshelf-api:latest
      ports:
            - "8080:8080"
      depends_on:
            - bookshelf-api-db
      environment:
            - DOCKER=true
            - DOCKER_DB_STRING=Server=bookshelf-api-db;Database=master;User=sa;Password=Password123;MultipleActiveResultSets=true;TrustServerCertificate=True

  bookshelf-api-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: bookshelf-api-db
        user: root
        ports:
            - "8081:1433"
        environment:
            MSSQL_SA_PASSWORD: "Password123"
            SA_PASSWORD: "Password123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        volumes:
             - ./db:/var/opt/mssql